### ISSUE TITLE
Good first bug: Use strrchr in a function

### ISSUE THREAD

**Issue by darnuria** [noalien/GL4Dummies#10]
In [GL4D/gl4dummies.c#L346-L359](https://github.com/noalien/GL4Dummies/blob/e68e55c69c52b193edc315cd1f98f84a8438022f/lib_src/GL4D/gl4dummies.c#L346-L359)

function `filenameOf` there is the following pattern of code:
```c
  int spos = -1, l;
  const char * ptr = path;
  char * tmp;
  while(*ptr) {
    if(*ptr == '/')
      spos = ptr - path;
    ++ptr;
  }
  tmp = malloc((l = (int)strlen(&path[++spos]) + 1) * sizeof *tmp);
```

It can be rewriten with `strrchr` [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/) standard C function conforming to

> POSIX.1-2001, POSIX.1-2008, C89, C99, SVr4, 4.3BSD.

`strrchr` will return a pointer to the last occurrence of a searched character in `path`, if we add one it will skip it... I think it's enough information for a motivated student.

Little ascii art of what we want.
````
/home/axel/superfile.txt\0
\                ^^- what we want $_$
^                \ returns of strrch
\ path
```

This contribution will improve readability and I am sure that `strrchr` in glibc use some vectorized instruction magic.

**Comment by darnuria** [comment]
Pour suivre #19 est arrivée en premier par https://github.com/noalien/GL4Dummies/pull/19 puis #22 et #23 sont arrivées. Avec 3 fix on devrait pouvoir faire quelque chose de parfait!

Plus sérieusement pensez a dire coucou sur l'issue ça permet de l'attribuer et de signaler a tout le monde que en cours de résolution comme ça on vous laisse un peu de temps sinon il y a des courses de données et 3 PR arrivent le même soir et je dois aider @noalien a trouver la bonne/merger. xD

**Comment by fiplox** [comment]
Bonjour :wave:
Alors, en regardant tout le repo avec `ripgrep` j'ai trouvé que la fonction `filenameOf()` est jamais appelé.  
@noalien Pourrait-on considérer de supprimer cette fonction?

**Comment by noalien** [comment]
Bonjour, c'est une fonction externe ; elle n'est donc pas nécessairement appelée dans la lib elle-même.

**Comment by darnuria** [comment]
Et bien c'est fait par https://github.com/noalien/GL4Dummies/pull/19 on peut close vaut mieux tard que jamais.
