### ISSUE TITLE
Ajouter `-Wextra` dans la configuration `autotools`

### ISSUE THREAD

**Issue by darnuria** [noalien/GL4Dummies#16]
Bonne première contribution très facile!

Dans le fichier [configure.ac#L56](https://github.com/noalien/GL4Dummies/blob/master/configure.ac#L56) ajouter l'option de compilation suivante `-Wextra` car `-Wall` ne contiens pas tout! :)

Citation de la [documentation de GCC sur les warnings](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html):

> -Wextra
>
>   This enables some extra warning flags that are not enabled by -Wall. (This option used to be called -W. The older name is still   supported, but the newer name is more descriptive.)
>
>    -Wclobbered  
>    -Wcast-function-type  
>    -Wdeprecated-copy (C++ only) 
>    -Wempty-body  
>    -Wignored-qualifiers 
>    -Wimplicit-fallthrough=3 
>    -Wmissing-field-initializers  
>    -Wmissing-parameter-type (C only)  
>    -Wold-style-declaration (C only)  
>    -Woverride-init  
>    -Wsign-compare (C only) 
>    -Wstring-compare 
>    -Wredundant-move (only for C++)  
>    -Wtype-limits  
>    -Wuninitialized  
>    -Wshift-negative-value (in C++03 and in C99 and newer)  
>    -Wunused-parameter (only with -Wunused or -Wall) 
>    -Wunused-but-set-parameter (only with -Wunused or -Wall)
>
>    The option -Wextra also prints warning messages for the following cases:
>
>        A pointer is compared against integer zero with <, <=, >, or >=.

**Comment by darnuria** [comment]
Bonjour et merci à @Bibi210, @derze et @laozey d'avoir contribuer.

Cependant avant d'ouvrir une Pull-Request l'usage est de dire bonjour et de s'assurer qu'on a bien compris de quoi il en retournais, comme indiqué dans vos reviews respectives. 

J'ai indiquer qu'il était de bon ton **d'ajouter** `-Wextra` et non **remplacer** `-Wall`.

Vous trouverez donc la définition du verbe [ajouter](https://www.dictionnaire-academie.fr/article/A9A1047) car il me semble que vous vous êtes trompé avec le verbe [remplacer](https://www.dictionnaire-academie.fr/article/A9R1631). J'ai pris la liberté d'ajouter les [adresses reticulaires](https://fr.wiktionary.org/wiki/adresse_r%C3%A9ticulaire) sur les mots **ajouter** et **remplacer** pour ne pas surcharger la lecture.

C'est possible dans l'empressement de se tromper mais vu que vous n'avez pas dit bonjour et avez sauter sur votre clavier je pense que vous méritiez bien que je vous enquiquine un peu ! ;p

Cependant merci d'avoir contribuer, j’espère que vous trouverez le temps de corriger vos PR ou d'aider un de vos camarade a corriger la sienne! ^_^

Si vous ne reconnaissez pas l’académie française comme une instance canonique pour le français voici les définitions d'[ajouter](https://usito.usherbrooke.ca/d%C3%A9finitions/ajouter) et [remplacer](https://usito.usherbrooke.ca/d%C3%A9finitions/remplacer) selon le dictionnaire de Français Quebecois en ligne fourni par l'Université de Sherbrooke.

**Comment by Bibi210** [comment]
Fix Issue 16 Essai N*2
Bonjour @darnuria Puis-je vous proposer mon aide afin de résoudre cette issue.
Il s'agit donc d'apporter une option de compilation supplémentaire "-Wextra" en plus de celle déjà présente "-Wall". 
Je vais donc essayer de travailler sur une modification du fichier "configure.ac" afin d'accéder a votre demande.

**Comment by darnuria** [comment]
Aucun soucis, pense à bien *ajouter* à côté de `-Wall` l'option `-Wextra` je passerais review ensuite.
