### ISSUE TITLE
/usr/lib/include/GL4D n'a pas les bonnes permissions sur certaines distributions

### ISSUE THREAD

**Issue by Phundrak** [noalien/GL4Dummies#2]
En installant GL4Dummies sur une nouvelle installation Void Linux, le répertoire `/usr/lib/include/GLD` n’avait pas les permissions nécessaires pour que les utilisateurs autres que `root` aient accès à son contenu (permissions `drwxr-x---`).
Un `chmod a+rx /usr/lib/include/GL4D` a été nécessaire. En revanche, aucun problème sur les permissions des fichiers contenus dans le répertoire. Peut-être serait-il possible d’ajouter cette commande `chmod` dans le Makefile lors de l’installation ?

**Comment by noalien** [comment]
Bonjour,

merci pour ce retour,

j'ai ajouté ces deux lignes dans le Makefile.am
 	chmod a+rx $(prefix)/include/GL4D
 	chmod a+r $(prefix)/include/GL4D/*

ça devrait corriger le problème,

par contre (je ne connais pas la distrib Void Linux) le chemin 
/usr/lib/include me semble bizarre, habituellement c'est /usr/lib (ou 
/usr/local/lib) pour les libs et /usr/include (ou /usr/local/include) pour 
les headers ...

--
Farès Belhadj
Associate Professor (MCF)
Responsable du Master 2 Informatique des Systèmes Embarqués
LIASD - UFR MITSIC - Université Paris 8
