### ISSUE TITLE
[CWE-690] possible-null-dereference GL4D/list.c fonction list_insert

### ISSUE THREAD

**Issue by darnuria** [noalien/GL4Dummies#21]
Déplacé de #13 pour suivre séparément. Concrètement faut checker ces mallocs.
```c
GL4D/list.c:87:17: warning: dereference of possibly-NULL ‘new_ptr’ [CWE-690] [-Wanalyzer-possible-null-dereference]
   87 |   new_ptr->data = malloc(list->data_size);
      |   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
  ‘list_insert’: events 1-4
    |
    |   72 |   for (i = 0; i < index; i++) {
    |      |   ^~~
    |      |   |
    |      |   (1) following ‘false’ branch (when ‘i >= index’)...
    |......
    |   86 |   new_ptr = malloc(sizeof *new_ptr);
    |      |             ~~~~~~~~~~~~~~~~~~~~~~~
    |      |             |
    |      |             (2) ...to here
    |      |             (3) this call could return NULL
    |   87 |   new_ptr->data = malloc(list->data_size);
    |      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    |      |                 |
    |      |                 (4) ‘new_ptr’ could be NULL: unchecked value from (3)
    |
```

Suggestion [assert](https://en.cppreference.com/w/c/error/assert). ;)

**Comment by Bibi210** [comment]
Re-Bonjour @darnuria J'aimerais vous proposer mon aide afin de résoudre cette issue.
Il s'agit donc de vérifier la bonne exécution de ses deux malloc.
Comme vous l'avez suggérer une fonction assert permettra de résoudre ce probleme
Je vais donc essayer si vous me le permettez de travailler sur une modification de la fonction "list_insert" dans le fichier "GL4D/list.c" afin d'accéder a votre demande.

**Comment by darnuria** [comment]
Super, hésite pas à faire une recherche via **Ctrl-shift-f** ou bien `rgrep` sur `assert` dans le code de la GL4Dummies pour voir des exemples d'usage de `assert` après un `malloc` qui ressemblent à notre soucis ici.
