### ISSUE TITLE
Problème d'Installation avec les Versions SDL2 > 2.0.0

### ISSUE THREAD

**Issue by Nawfoel-Ardjoune** [noalien/GL4Dummies#26]
Bonjour j'ai relevé un problème lors de l'installation de GL4dummies à l'étape de l'exécution du ./configure.
Ce problème survient lorsque l'on n'a pas la version de SDL2 2.0.0. J'ai essayé avec la dernière version de SDL2 2.0.14 et l'exécutable ne trouve pas les fichiers de SDL2.

**Je suis sur Mac Big Sure version 11.1**
**J'utilise Macport pour installer toutes les dépendances y compris SDL2**

Pour régler ce problème il suffit de se rendre sur le site de SDL2 et de télécharger la version 2.0.0
En attendant un fix (que j'espère vous faire) :)

**Comment by noalien** [comment]
Bonjour, je ne crois pas que ce problème soit à régler du côté de la lib GL4D ; il s'agit plus d'une mauvaise configuration de votre installation de SDL2. Merci de me fournir plus d'éléments justifiant l'ouverture d'une Issue.

**Comment by Nawfoel-Ardjoune** [comment]
Monsieur Viala m'a conseiller d'ouvrir une issue pour vous faire part de ce petit problème et vous demander si je pouvais vous aider dans le cadre de son cours de Logiciel Libre

**Comment by noalien** [comment]
je n'ai rien contre l'initiative de participer ici à l'amélioration de GL4D. C'est juste que concernant ce que vous relevez comme étant un Bug dans GL4D je considère que c'est un problème d'installation de la dépendance.

**Comment by Nawfoel-Ardjoune** [comment]
OK j'ai corrigé le post

**Comment by Marobax** [comment]
Je confirme @noalien, je suis avec la SDL 2.0.10 (sur Kubuntu) et aucun problème d'installation. Le problème ne vient pas de la librairie. On ferme cette issue ?

**Comment by noalien** [comment]
Je suis d'accord oui. Merci
