### ISSUE TITLE
Wrong assert in gl4duMultMatrixd

### ISSUE THREAD

**Issue by Marobax** [noalien/GL4Dummies#28]
## Function `gl4duMultMatrixd` in `GL4D/gl4du.c`

I've found a typo, here. At least i think so.

Contrary to its sister function `gl4duMultMatrixf`, the function `gl4duMultMatrixd` (notice the "d" instead of "f") should handle `double` type matrix instead of `float`.

Looking at some asserts in `gl4duMultMatrixf`, it checks if the current matrix is actually based on floats. And so is `gl4duMultMatrixd`... which is, wrong ?

I guess a typo happenned when copying the `float` function to make the `double` one.

This should do the job :)
```diff
void gl4duMultMatrixd(const GLdouble * matrix) {
    GLdouble * mat, cpy[16];
    assert(_gl4dCurMatrix);
-   assert(_gl4dCurMatrix->type == GL_FLOAT);
+   assert(_gl4dCurMatrix->type == GL_DOUBLE);
    mat = (GLdouble *)&(((GLubyte *)_gl4dCurMatrix->data)[_gl4dCurMatrix->top * _gl4dCurMatrix->size]);
    memcpy(cpy, mat, _gl4dCurMatrix->size);
    MMAT4XMAT4(mat, cpy, matrix);
}
```

**Comment by noalien** [comment]
Correct, thanks for reporting this issue

**Comment by darnuria** [comment]
@Marobax would work on a pull request? :)

**Comment by darnuria** [comment]
Oh look like a young one tackled it first ;P

https://github.com/noalien/GL4Dummies/pull/29

**Comment by darnuria** [comment]
La partie fun c'est:
https://github.com/noalien/GL4Dummies/blob/master/lib_src/GL4D/gl4dummies.h#L116
```
lib_src/GL4D/gl4dummies.h
116:#define GL_DOUBLE GL_FLOAT
```

**Comment by Marobax** [comment]
![contemplating suicide](https://i.imgur.com/1BH123a.jpg)

**Comment by noalien** [comment]
It's included in a:
"#ifdef __ANDROID__"
no worries

**Comment by darnuria** [comment]
Thanks @fiplox and @Marobax !
