### ISSUE TITLE
[Trivial] Add a vsync flag for gl4duwCreateWindow

### ISSUE THREAD

**Issue by ObaniGemini** [noalien/GL4Dummies#7]
ATM, to enable **vsync**, you have to pass _SDL_RENDERER_PRESENTVSYNC_ to _gl4duwCreateWindow_, but it doesn't feel right to use a SDL flag to a gl4d function even tho the flags are only used for  _SDL_CreateWindow_.

I think it's a really important feature when you want to have your app and other stuff running at the same time, even for just modifying a shader on the go, and it would be great to have it nicely implemented in GL4D.

Thanks for reading!

**Comment by Marobax** [comment]
Actually, to enable vsync you have to pass `SDL_RENDERER_PRESENTVSYNC` to `SDL_CreateRenderer`, not `gl4duwCreateWindow`. And knowing that a function like "gl4dCreateRenderer" (to wrap `SDL_CreateRenderer`) doesn't exist, it's pretty normal if its flags doesn't exist too.

A more appropriate thing to do could be creating a "gl4dCreateRenderer" function and _then_ the appropriate flags ;)
