### ISSUE TITLE
Some sign comparaison warnings

### ISSUE THREAD

**Issue by darnuria** [noalien/GL4Dummies#8]
Edited makefile to add `-Wextra` and get some good first bug candidates for motivated students like we have at paris8! ;)

## Function `aes_from_tar` in `GL4D/aes`

```c
GL4D/aes.c: In function ‘aes_from_tar’:
GL4D/aes.c:915:56: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘__off_t’ {aka ‘long int’} [-Wsign-compare]
  915 |   if( (l = fread(data, sizeof * data, buf.st_size, f)) != buf.st_size) {
      |                                                        ^~
```

It's sign comparison warning due to the fact that `struct stat` has a field of type `st_size` of type `off_t` which is signed...
May be a good first bug for a studen to wrap `st_size` access in an inlinable function who return file size in a `size_t` type. ;)

Good question about that:
https://stackoverflow.com/questions/12275831/why-is-the-st-size-field-in-struct-stat-signed

## Function `ccl` in `GL4D/gl4dfCanny`

```c
GL4D/gl4dfCanny.c: In function ‘ccl’:
GL4D/gl4dfCanny.c:119:15: warning: comparison of integer expressions of different signedness: ‘GLint’ {aka ‘int’} and ‘long unsigned int’ [-Wsign-compare]
  119 |  for(j = 0; j < sizeof d / sizeof *d; ++j) {
      |               ^
```

**Comment by Marobax** [comment]
I just corrected the this issue in the PR #32. Without the inline function you suggested @darnuria, i must admit.
